### PR TITLE
bug fixed & enhancement

### PR DESCRIPTION
**Pull request by atom2ueki**
##### bug fixed
bug fixed for
https://github.com/jsdf/react-native-refreshable-listview/issues/32
https://github.com/jsdf/react-native-refreshable-listview/issues/27

##### enhancement - New props/attributes added

`pullingIndicator: oneOfType([func, element])`  - define the indicator shown when pulling down  ( optional )
`holdingIndicator: oneOfType([func, element])` - define the indicator shown when pulling down and holding after it exceed the min-distance ( optional )
`refreshingIndicator: oneOfType([func, element])` - define the indicator shown when refreshing ( optional )
`pullingPrompt: String` default 'pull to refresh'
`holdingPrompt: String` default 'release to refresh'
`refreshingPrompt: String` default 'loading'

##### new example added
please refer to this example to learn how to use the version of this PR

### CODE REVIEW

**Comment by atom2ueki** [comment]
@jsdf I'm not sure how to pass travis-ci/pr

**Comment by niftylettuce** [comment]
Can we get this merged?

**Comment by jsdf** [comment]
That's the plan

**Comment by niftylettuce** [comment]
Getting these errors, not sure if you guys can reproduce?

screen shot 2015-12-08 at 4 43 32 pm

**Comment by jsdf** [comment]
Okay so I finally got some time to pull down this branch and take a look at it, and I think some of the new features need a bit of polish but I'm mindful that people want the bug fixes so I'm just going to merge those for now.

**Comment by atom2ueki** [comment]
@jsdf any news on this ?

**Comment by jsdf** [comment]
Sorry I'm just on holiday at the moment, back this weekend

**Comment by atom2ueki** [comment]
@jsdf no problem, enjoy

**Comment by natorojr** [comment]
@atom2ueki If you have time, it might be worth separating the bug fix from the enhancement. That way @jsdf can focus on reviewing and merging the bug fix with higher priority (since presumably it involves less code) and then give feedback on the enhancement when he has time.

Just my $0.02

**Comment by jsdf** [comment]
Ah it's okay, I'm going to fix both at the same time (though with a
different API for passing in the stuff to be rendered for the various
states) because both are release blockers for v2. I'll just manually merge
this code, leaving out the parts which aren't needed.

**Pull request merged**
